MODULE forwardtest;
 
TYPE T0 = RECORD END;
 
PROCEDURE^(VAR r: T0) P; 
PROCEDURE^(VAR r: T0) P; 
PROCEDURE (VAR r: T0) Q; BEGIN END Q;
 
PROCEDURE^P;
PROCEDURE^P;
PROCEDURE P; BEGIN END P;
 
END forwardtest.
