MODULE Client;
IMPORT S:=Server; 

TYPE P* = POINTER TO T;
     T* = RECORD(S.T) END;


PROCEDURE (VAR r:T)P1*; BEGIN END P1;
PROCEDURE (VAR r:T)P0; BEGIN END P0;
PROCEDURE (VAR r:T)P2*; BEGIN END P2;

END Client.
