MODULE OpenNew;

TYPE T=CHAR;
VAR a1:POINTER TO ARRAY OF T;
    a2:POINTER TO ARRAY OF ARRAY OF T;
    a3:POINTER TO ARRAY OF ARRAY OF ARRAY OF T;
    a4:POINTER TO ARRAY OF ARRAY OF ARRAY OF ARRAY OF T;
    i:SHORTINT; 

PROCEDURE Alloc*;
BEGIN (* Alloc *)
 i:=1; 
 NEW(a1,i); 
 NEW(a2,2,3); 
 NEW(a4,2,2,2,2); 
 NEW(a3,2,3,4); 
END Alloc;

END OpenNew.
