FOREIGN MODULE UTIS;

IMPORT SYSTEM;

PROCEDURE Length*(s:ARRAY OF CHAR):LONGINT; END Length;
PROCEDURE Delete*(VAR str:ARRAY OF CHAR; inx,len:LONGINT); END Delete;
PROCEDURE DoFillLb*(VAR s:ARRAY OF CHAR; len:LONGINT; c:CHAR); END DoFillLb;
PROCEDURE DoFillRb*(VAR s:ARRAY OF CHAR; len:LONGINT; c:CHAR); END DoFillRb;
PROCEDURE Ptr2Int*(ptr:SYSTEM.PTR):LONGINT; END Ptr2Int;
PROCEDURE Int2Dez*(val:LONGINT; VAR s:ARRAY OF CHAR); END Int2Dez;
PROCEDURE Int2Hex*(val:LONGINT; VAR s:ARRAY OF CHAR); END Int2Hex;

END UTIS.
